module ALU_INCREMENTER(INC,CARRY,SIGN,ZERO,PARITY,OVERFLOW,A);
input [15:0]A;
output [15:0]INC;
output CARRY;
output SIGN;
output ZERO;
output PARITY;
output OVERFLOW;

ALU_ADDER_16BIT ADD(.SUM(INC),
.CARRY(CARRY),.SIGN(SIGN),
.ZERO(ZERO),.PARITY(PARITY),
.OVERFLOW(OVERFLOW),.A(A),
.B(16'b0000),.CIN(1'B1));

endmodule
